[package]
name = "cargo-watch"
version = "5.1.1"

authors = ["Félix Saparelli <felix@passcod.name>"]
categories = ["command-line-utilities", "development-tools"]
description = "Watches over your Cargo project’s source"
homepage = "https://github.com/passcod/cargo-watch"
keywords = ["cargo", "watch", "compile", "notify"]
license = "CC0-1.0"
readme = "README.md"
repository = "https://github.com/passcod/cargo-watch"

[dependencies]
clap = "2.22.1"
watchexec = "~1.8.5"
