[package]
name = "cargo-watch"
version = "2.1.3"
authors = [
  "Félix Saparelli <me@passcod.name>",
  "Antti Keränen <detegr@gmail.com>",
  "Konstantin Stepanov <me@kstep.me>",
  "Jonathan Neuschäfer <j.neuschaefer@gmx.net>",
  "Gabor Nagy <mail@aigeruth.hu>",
]

description = "Utility for cargo to compile projects when sources change"
homepage = "https://github.com/passcod/cargo-watch"
repository = "https://github.com/passcod/cargo-watch"

readme = "README.md"
license = "CC0-1.0"
keywords = [
  "cargo",
  "watch",
  "compile",
  "notify"
]

[dependencies]
rustc-serialize = "*"
docopt = "0.6"
docopt_macros = "0.6"
notify = "^2.0.0"
regex = "*"
time = "*"
