[package]
name = "cargo-watch"
version = "7.2.1"

authors = ["Félix Saparelli <felix@passcod.name>"]
categories = ["command-line-utilities", "development-tools"]
description = "Watches over your Cargo project’s source"
homepage = "https://github.com/passcod/cargo-watch"
keywords = ["cargo", "watch", "compile", "notify"]
license = "CC0-1.0"
readme = "README.md"
repository = "https://github.com/passcod/cargo-watch"

[badges]
travis-ci = { repository = "passcod/cargo-watch" }
maintenance = { status = "passively-maintained" }

[profile.release]
lto = true
panic = "abort"
codegen-units = 1

[dependencies]
clap = "2.33.0"
watchexec = "1.10.2"

[dev-dependencies]
assert_cmd = "0.11.1"
insta = "0.8.1"
predicates = "1.0.1"
wait-timeout = "0.2.0"

# TODO:
# remove this if/when https://github.com/watchexec/watchexec/pull/134 is
# merged and a new version of watchexec is released
[patch.crates-io.watchexec]
git = 'https://github.com/waynr/watchexec'
branch = 'issue133-leave-handler-initialization-to-watch-caller'
