[package]
name = "cargo-watch"
version = "3.0.1"
authors = [
  "Félix Saparelli <me@passcod.name>",
  "Antti Keränen <detegr@gmail.com>",
  "Konstantin Stepanov <me@kstep.me>",
  "Jonathan Neuschäfer <j.neuschaefer@gmx.net>",
  "Gabor Nagy <mail@aigeruth.hu>",
  "Ivan Jager <aij+git@mrph.org>",
  "Christopher Brickley <brickley@gmail.com>",
]

description = "Utility for cargo to compile projects when sources change"
homepage = "https://github.com/passcod/cargo-watch"
repository = "https://github.com/passcod/cargo-watch"

readme = "README.md"
license = "CC0-1.0"
keywords = [
  "cargo",
  "watch",
  "compile",
  "notify"
]

[dependencies]
docopt = "^0.6"
env_logger = "^0.3"
log = "^0.3"
notify = "^2.4.1"
regex = "*"
rustc-serialize = "*"
time = "*"

[features]
notifications = ["notify-rust"]

[dependencies.notify-rust]
version = "~3.0"
optional = true
